### ISSUE TITLE
Remove equal translations from output

### ISSUE THREAD

**Issue by willbasky** [willbasky/TibetCli#22]
Some dictionaries have the same keys and different values. It is ok.
But ones have same keys and same values, and them all come to output. It is not ok.

**Comment by gera-cameron** [comment]
I'll pick this one up too start!

**Comment by willbasky** [comment]
For example.

```
$ tibet shell
What tibetan word to translate?
> sems
...
9. CommonTerms-Lin
༔ mind
༔ mind
༔ mind
༔ mind
...
```

**Comment by willbasky** [comment]
@gera-cameron How do you do?
